payload_patch = {'authorised_signatory': {'address': {'city': 'bekasi',
                                      'district': 'pondok gede bage haduha',
                                      'postal_code': '17424',
                                      'province': 'LAMPUNG',
                                      'rt': '007',
                                      'rw': '013',
                                      'street_address': 'Jalan kenangan',
                                      'village': 'jatimekar'},
                          'bank_account': {'holder_name': 'Nama Saya',
                                           'number': '21312432439',
                                           'swift_code': 'BMRIIDJA'},
                          'birth_date': '1995-11-01T00:00:00.000Z',
                          'birth_place': 'Jakarta',
                          'business_type': 'OTHER',
                          'documents': {'ktp': {'number': '1234561109900004'},
                                        'npwp': {},
                                        'selfie': {}},
                          'domicile': 'ID',
                          'education': 'BACHELORS_DEGREE',
                          'email': 'arqdai1@mailinator.com',
                          'emergency_contact_name': 'Dadang',
                          'emergency_contact_number': '+6281375384352',
                          'first_name': 'Ardi aL',
                          'gender': 'MALE',
                          'housing_status': 'OWN_HOME',
                          'job': 'PRIVATE_SECTOR_EMPLOYEE',
                          'last_name': 'berkah jaya jaya jaya',
                          'marital_status': 'SINGLE',
                          'mobile_number': '+6285740001122',
                          'monthly_income_range': 'GTE_5_AND_LT_10_MILLION',
                          'mother_maiden_name': 'Emak',
                          'religion': 'CONFUCIAN',
                          'source_of_fund': 'SALARY',
                          'title': 'SDR'},
 'partner_id': '7cffcfa2-05ae-4805-a16f-68159f1b6f71',
 'type': 'PERSONAL'}




payload_repatch = {'authorised_signatory': {'address': {'city': 'bekasi',
                                      'district': 'pondok gede bage',
                                      'postal_code': '17424',
                                      'province': 'LAMPUNG',
                                      'rt': '007',
                                      'rw': '013',
                                      'street_address': 'Jalan kenangan',
                                      'village': 'jatimekar'},
                          'bank_account': {'holder_name': 'Nama Saya',
                                           'number': '21312432439',
                                           'swift_code': 'BMRIIDJA'},
                          'birth_date': '1995-11-01T00:00:00.000Z',
                          'birth_place': 'Jakarta',
                          'business_type': 'OTHER',
                          'documents': {'ktp': {'number': '1234561109900004'},
                                        'npwp': {},
                                        'selfie': {}},
                          'domicile': 'ID',
                          'education': 'BACHELORS_DEGREE',
                          'email': 'arqdai1@mailinator.com',
                          'emergency_contact_name': 'Dadang',
                          'emergency_contact_number': '+6281375384352',
                          'first_name': 'Ardi aL',
                          'gender': 'MALE',
                          'housing_status': 'OWN_HOME',
                          'job': 'PRIVATE_SECTOR_EMPLOYEE',
                          'last_name': 'berkah jaya jaya jaya',
                          'marital_status': 'SINGLE',
                          'mobile_number': '+6285740001122',
                          'monthly_income_range': 'GTE_5_AND_LT_10_MILLION',
                          'mother_maiden_name': 'Emak',
                          'religion': 'CONFUCIAN',
                          'source_of_fund': 'SALARY',
                          'title': 'SDR'},
 'partner_id': '7cffcfa2-05ae-4805-a16f-68159f1b6f71',
 'type': 'PERSONAL'}




